[project]
name = "ortho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ethan Hadley", email = "ekhadley@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "cloudpickle>=3.1.2",
    "flash-linear-attention>=0.5.2",
    "inspect-ai==0.3.273",
    "ipykernel>=7.3.0",
    "mechtools",
    "nbformat>=5.11.1",
    "openai>=3.22.1",
    "pyyaml>=6.0.3",
    "rhenvs",
]

[tool.uv.sources]
mechtools = { git = "ssh://git@github.com/ekhadley/mechtools" }
rhenvs = { git = "https://github.com/ekhadley/rh-envs" }
